---
title: "Graphs"
execute:
  echo: FALSE
  message: FALSE
  warning: FALSE
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(primer.data)
library(gtsummary)
library(brms)
library(tidybayes)
library(gt)
library(tidyr)
library(ggplot2)
library(dplyr)
```

```{r}
#| message: false

df <- read_csv("data/mxmh_survey_results.csv")
```

```{r}
df_filtered <- df |> 
  rename(music_effects = "Music effects",
         fav_genre = "Fav genre",
         depression = "Depression",
         anxiety = "Anxiety",
         insomnia = "Insomnia",
         ocd = "OCD") |> 
  select(fav_genre, depression, anxiety, insomnia, ocd, music_effects) |> 
  filter(!is.na(fav_genre), 
         !is.na(depression), 
         !is.na(music_effects), 
         !is.na(anxiety), 
         !is.na(insomnia), !is.na(ocd))
```

```{r}
df_filtered$depression <- as.numeric(df_filtered$depression)

df_filtered$anxiety <- as.numeric(df_filtered$anxiety)

df_filtered$insomnia <- as.numeric(df_filtered$insomnia)

df_filtered$ocd <- as.numeric(df_filtered$ocd)
```

### Graphs Based on Average Depression Level

These graphs showcase the average levels for each mental health condition based on their favorite genre.

```{r}
green_colors <- c("#C1E3D7", "#C8E6C9", "#A5D6A7", "#81C784", "#66BB6A", 
                   "#4CAF50", "#43A047", "#388E3C", "#2C6B50", "#1B5E20", 
                   "#004D40", "#00796B", "#004D40", "#003B4F", "#002F3F", 
                   "#00251A")

ggplot(df_filtered, aes(x = fav_genre, 
                        y = anxiety,
                        fill = fav_genre)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9),
           width = 0.7) +
  scale_fill_manual(values = green_colors) +
  labs(x = "", 
       y = "Average Anxiety Level", 
       title = "Anxiety Scores by Favorite Music Genre") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1),
                                   legend.position = "none")
```

```{r}
red_colors <- c("#F8BBD0", "#FFCDD2", "#EF9A9A", "#E57373", "#EF5350", 
                 "#F44336", "#E53935", "#D32F2F", "#C62828", "#B71C1C", 
                 "#FF8A80", "#FF5252", "#FF1744", "#D50032", "#C62828", 
                 "#B71C1C")

ggplot(df_filtered, aes(x = fav_genre, 
                        y = insomnia,
                        fill = fav_genre)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9), 
           width = 0.7) +
  scale_fill_manual(values = red_colors) +
  labs(x = "", 
       y = "Average Insomnia Level", 
       title = "Insomnia Scores by Favorite Music Genre") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1),
                                   legend.position = "none")
```

```{r}
purple_colors <- c("#E1BEE7", "#D1A9D1", "#CE93D8", "#BA68C8", "#AB47BC", 
                    "#9C27B0", "#8E24AA", "#7B1FA2", "#6A1B9A", "#4A148C", 
                    "#F8BBD0", "#F48FB1", "#F06292", "#EC407A", "#D81B60", 
                    "#C2185B")

ggplot(df_filtered, aes(x = fav_genre, 
                        y = ocd,
                        fill = fav_genre)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9), 
           width = 0.7) +
  scale_fill_manual(values = purple_colors) +
  labs(x = "", 
       y = "Average OCD Level", 
       title = "OCD Scores by Favorite Music Genre") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1),
                                   legend.position = "none")
```

### Graphs Based on Effects of the Music

These graphs demonstrate the average mental health levels of respondents that answered the genre of music improved, had no effect on, or worsened their mental health level.

```{r}
ggplot(df_filtered, aes(x = fav_genre, 
                        y = depression,
                        fill = music_effects)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9), 
           width = 0.7) +
  labs(x = "",
       y = "Average Depression Level",
       title = "Depression Scores by Favorite Music Genre and Music Effects",
       fill = "Music effects") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1))
```

```{r}
ggplot(df_filtered, aes(x = fav_genre, 
                        y = anxiety, 
                        fill = music_effects)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9),
           width = 0.7) +
  labs(x = "", 
       y = "Average Anxiety Level", 
       title = "Anxiety Scores by Favorite Music Genre and Music Effects", 
       fill = "Music effects") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1))
```

```{r}
ggplot(df_filtered, aes(x = fav_genre, 
                        y = insomnia, 
                        fill = music_effects)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9), 
           width = 0.7) +
  labs(x = "", 
       y = "Average Insomnia Level", 
       title = "Insomnia Scores by Favorite Music Genre and Music Effects", 
       fill = "Music effects") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1))
```

```{r}
ggplot(df_filtered, aes(x = fav_genre, 
                        y = ocd, 
                        fill = music_effects)) +
  geom_bar(stat = "summary", 
           fun = "mean", 
           position = position_dodge(0.9), 
           width = 0.7) +
  labs(x = "", 
       y = "Average OCD Level", 
       title = "OCD Scores by Favorite Music Genre and Music Effects", 
       fill = "Music effects") +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1))
```
